### ISSUE TITLE
ShellPhish

### ISSUE THREAD

**Issue by byanonyms** [thelinuxchoice/shellphish#17]

**Comment by ItsAlex42** [comment]
**What's the issue!?**

**Comment by byanonyms** [comment]
No problem.

21 Nis 2020 Sal ÖS 12:01 tarihinde Alex42 <notifications@github.com> şunu
yazdı:

**Comment by ItsAlex42** [comment]
Ｂｒｕｈ

**Comment by byanonyms** [comment]
Ne diyon

21 Nis 2020 Sal ÖS 12:11 tarihinde Alex42 <notifications@github.com> şunu
yazdı:

**Comment by ItsAlex42** [comment]
Close issue

**Comment by byanonyms** [comment]
Türkçe konuş

21 Nis 2020 Sal ÖS 12:20 tarihinde Alex42 <notifications@github.com> şunu
yazdı:
