### ISSUE TITLE
Generated link is not working

### ISSUE THREAD

**Issue by avlearner** [thelinuxchoice/shellphish#19]
![Screenshot_2020-04-23-16-37-05-859_com android chrome](https://user-images.githubusercontent.com/64201232/80092783-00dd4d00-8581-11ea-8258-1eee3ab81246.jpg)
What to do? Please help.

**Comment by Aryanverma18** [comment]
Ye

**Comment by Aryanverma18** [comment]
It open sometimes but sometimes it show this
