### ISSUE TITLE
Ngork link is not generated. 

### ISSUE THREAD

**Issue by vinod3070** [thelinuxchoice/shellphish#3]
[*] Choose an option: 1
[*] Downloading Ngrok...
[*] Starting php server...
[*] Starting ngrok server...
[*] Send this link to the Victim: 
[*] Waiting victim open the link ...

The ngork link is not being generated. any faced this issue ??

**Comment by dynamo-Anon** [comment]
I am having the exact same issue, has anyone come up with a fix for this yet?

**Comment by vinod3070** [comment]
@Aletered-Carbon the issue is with the ngrok installed on your box. Try using another tool related to ngrok or ngrok directly. You'll still not be able to generate the link.

**Comment by thelinuxchoice** [comment]
try new version with Serveo option

**Comment by Rajeshwar40** [comment]
no link is been generated for shellphish can anyone suggest how to fix this?
[*] Downloading Ngrok...
[*] Starting php server...
[*] Starting ngrok server...
[*] Send this link to the Victim: 

[*] Waiting IPs and Credentials, Press Ctrl + C to exit...

**Comment by rahman-R** [comment]
iam also facing the same problem guys........
i installed Ngrok
but it showing the same problem the link is not generated

**Comment by forbesgriffin** [comment]
Am also facing the same problem

**Comment by awaisronaldo** [comment]
Try install pkg install openssh and then check it

**Comment by KumarAtulJaiswal** [comment]
i am also facing the same problem :( www.hackingtruth.in

**Comment by joker-man-maker** [comment]
Same problem

**Comment by johndoehack** [comment]
for ngrok you need to get your api key by registering. and serveo seems like having lots of problems lately

**Comment by habib2022sahil** [comment]
How im not understand
