### ISSUE TITLE
can you make it verify if the password is correct before receiving ?! 

### ISSUE THREAD

**Issue by minanagehsalalma** [thelinuxchoice/shellphish#4]
like  redirect the user to the official login page with the same pass and user name that he has entered .. and if it's correct sign him in it .. if not just ask him to reenter it ?

pls 
cheers

**Comment by minanagehsalalma** [comment]
@thelinuxchoice

**Comment by thelinuxchoice** [comment]
this is only useful for incorrect typed passwords, too much work for little return, but feel free to do this feature.

**Comment by minanagehsalalma** [comment]
no ii don't have the enough knowledge to do so !!!😥unfortunately
